# Playbook for mesos-dns clients
---

- name: Resolving DNS server IP
  shell: ping -c 1 {{ dns_host }} | grep -ohE "\(([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\)" | head -1 | sed "s/[()]//g"
  register: dns_server_ip

- name: Configuring dhclient for mesos-dns
  sudo: yes
  lineinfile: dest=/etc/dhcp/dhclient.conf regexp='^prepend domain-name-servers ' line='prepend domain-name-servers {{ dns_server_ip.stdout }};'
  notify:
    - restart dhclient
