# Playbook for mesos-dns clients
---

# TODO: don't override existing DNS server
# TODO: `grep nameserver /etc/resolv.conf | head -1 | awk '{print $2}'` returns the existing one
- name: Resolving DNS server IP
  shell: |
         DNS_SERVERS=""
         for HOST in {{ dns_hosts }}; do
           IP=$(ping -c 1 $HOST | grep -ohE "\(([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\)" | head -1 | sed "s/[()]//g")
           if [ "$DNS_SERVERS" = "" ]; then
             DNS_SERVERS="$IP"
           else
             DNS_SERVERS="$DNS_SERVERS,$IP"
           fi
         done
         echo $DNS_SERVERS
  register: dns_servers_ips

- name: Configuring dhclient for mesos-dns
  sudo: yes
  lineinfile: dest=/etc/dhcp/dhclient.conf regexp='^prepend domain-name-servers ' line='prepend domain-name-servers {{ dns_servers_ips.stdout }};'
  notify:
    - restart dhclient
