---
# Playbook for mesos-dns clients
- name: Configuring dhclient for mesos-dns
  sudo: yes
  lineinfile: dest=/etc/dhcp/dhclient.conf regexp='^prepend domain-name-servers ' line='prepend domain-name-servers {{ hostvars[dns_host].servicehost.stdout }};'
  notify:
    - restart dhclient
