---
- name: Download mesos-dns release
  get_url: url="{{ mesos_dns_release_path }}"
           dest="/usr/local/mesos-dns.gz"

- name: Extract mesos-dns release
  command: gzip -d -f /usr/local/mesos-dns.gz

- name: Add execution permission to mesos-dns
  file: path=/usr/local/mesos-dns state=file mode="u+x,g+x"

#TODO(jdef) once mesos-dns supports ZK detection we can check for /etc/mesos/zk

- name: Examining host IP configuration
  shell: ip -o -f inet addr show
           $(ip route | grep -e ^default.via | sed -e 's/.*dev //g') |
           head -1 | awk '{ print $4; }' | cut -f1 -d/
  register: servicehost

- set_fact:
    servicehost: "{{ servicehost }}"

- name: Configuring mesos-dns
  template: src=config.json.j2 dest={{ ansible_env.HOME }}/mesos-dns-config.json mode=0644

- name: Generating Marathon deployment descriptor
  template: src=mesos-dns.json.j2 dest={{ ansible_env.HOME }}/mesos-dns-app.json mode=0644

- name: Updating mesos-dns application deployment in Marathon
  shell: >
    curl -s -XPUT -H"Content-Type: application/json" http://{{ marathon }}/v2/apps/mesos-dns -d@{{ ansible_env.HOME }}/mesos-dns-app.json
